type: pages
headline: pagine del sito

size: small
info: "{{ page.category }}"
layout: cards

empty: No projects yet
image:
  extends: sections/image
  label: Team Member Photo
  min: 1
  max: 1
  image:
    ratio: 1/1
    cover: true

