# title: Site

# tabs:
#   # Content
#   content:
#     label: Content
#     icon: text
#     columns:
#       - width: 2/3
#         sections:

#           pages:
#             headline:
#               en: Pages
#               de: Seiten
#             type: pages
#             # templates:
#             #   - default
#             # create:
#             #   - default

#       - width: 1/3
#         sections:

#           files:
#             headline:
#               en: Global files
#               de: Globale Dateien
#             type: files

#           additional:
#             type: fields
#             fields:
#               gap:
#                 type: gap
  
#   # Contact
#   contact: tabs/seo/contact

#   # Matomo
#   matomo: tabs/matomo


options:
  title: false
  status: false
  duplicate: false
  url: false
  delete: false
  

columns:
  - width: 1/3
    sections:
      info:
        headline: Info
        type: info
        theme: white
        text: |
          Sezione amministrazione organizzazione e supervisione dei contenuti.

          -> https://www.studiosigna.com/

          Every aspect of the Panel interface can be customized with our blueprints and plugins. You can find out more about all the possibilities in our **(link: https://getkirby.com/docs/guide/blueprints/introduction text: docs)**.

          The Panel setup cannot be changed in the Panel though. If you want to play around with blueprints and templates, you should install the **(link: https://github.com/getkirby/starterkit text: Starterkit)** on your own machine.

  - width: 2/3
    sections:
      pages:
          extends: sections/site
        # size: small
        # extends: pages
    
